[build]
  publish = "_site"
  command = "DEBUG=* eleventy"

[[redirects]]
  from = '/resume'
  to = 'https://www.notion.so/arihant/Arihant-Verma-88508cf57c38404ebdfb2a3f2bfd6877'
  status = 200
  force = true
